name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Xcode 11.5
      run: |
        sudo xcode-select -s /Applications/Xcode_11.5.app/Contents/Developer
        xcodebuild -version
        xcrun instruments -s devices
        
    - uses: actions/checkout@v2

    - name: Build macOS target
      run: |
        xcodebuild clean build -project Csaifu.xcodeproj -scheme Csaifu -destination "platform=macOS,OS=10.15" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
    - name: Build iOS target
      run: |
        xcodebuild clean build -project Csaifu.xcodeproj -scheme Csaifu-iOS -sdk iphonesimulator -arch x86_64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

